### ISSUE TITLE
Only works for 24-36 hours

### ISSUE THREAD

**Issue by stk21** [freakent/node-red-contrib-sunevents#25]
I have noticed that since the update to 3.x and the new flow, the node will crash after running for some time, even if injecting lat/lon to keep it up and running.

Actually it will continue to run, but the payload output changed from the label to just 0.  Debug example below.  

3/18/2021, 7:36:53 PMnode: bf0d830e.31aef
sun_events_test : msg.payload : Object
{ value: 1616116747213, sunevent: "dusk" }

3/18/2021, 8:08:12 PMnode: bf0d830e.31aef
sun_events_test : msg.payload : Object
{ value: 1616116747213, sunevent: "nauticalDusk" }

3/18/2021, 8:40:00 PMnode: bf0d830e.31aef
sun_events_test : msg.payload : Object
{ value: 1616116747213, sunevent: "night" }

3/19/2021, 1:08:20 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : Object
{ value: 1616116747213, sunevent: "nadir" }

3/19/2021, 5:34:56 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : number
0

3/19/2021, 6:06:47 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : number
0

3/19/2021, 6:38:08 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : number
0

3/19/2021, 7:04:57 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : number
0

3/19/2021, 7:07:43 AMnode: bf0d830e.31aef
sun_events_test : msg.payload : number
0

**Comment by freakent** [comment]
I've not been able to recreate this issue in testing, but I have performed a few extra checks. I've just pushed a new version. Please give v3.0.3 a try.

**Comment by freakent** [comment]
I believe this is the same as issue #24 which has been addressed by v3.0.3. Please advise if v3.0.3 solves this issue for you so I can close off this issue.

**Comment by stk21** [comment]
Ill check it out.  I however dont see 3.0.3 as an option to upgrade to.  The palette still shows 3.0.2 and installing from the CLI still installs 3.0.2.

**Comment by stk21** [comment]
This is a node-red add-on install in hass-io.  But I can get into the container directly.

**Comment by freakent** [comment]
Did you manage to upgrade to v3.0.3 yet? I triggered a refresh in the node-red nodes catalog so it would pick up the change.

**Comment by freakent** [comment]
No further issues reported so I am assuming this is resolved.
